name: Storybook CI

on:
  push:
    branches: [feature/ui-components]
  workflow_dispatch:

env:
  NODE_VERSION: '16.x'
  AZURE_ACCOUNT_NAME: 'stdfxstbdev'
  AZURE_CDN_PROFILE: 'cdnp-dfx-stb-dev'
  AZURE_CDN_ENDPOINT: 'cdne-dfx-stb-dev'
  AZURE_RESOURCE_GROUP: 'rg-dfx-stb-dev'

jobs:
build:
  name: Build and deploy to DEV
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.DEV_CREDENTIALS }}

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install packages
      run: |
        npm ci

    - name: Build code
      run: |
        npm run build-storybook

    - name: Deploy to Azure Storage (DEV)
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch --account-name ${{ env.AZURE_ACCOUNT_NAME }} -d '$web' -s ./storybook-static --overwrite

    - name: Purge CDN endpoint (DEV)
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az cdn endpoint purge --content-paths  "/*" --profile-name ${{ env.AZURE_CDN_PROFILE }} --name ${{ env.AZURE_CDN_ENDPOINT }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }}

    - name: Logout
      run: |
        az logout
      if: always()
